name: Java Build on Windows

on:
  push:
    branches:
      - main
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # 3. Compile Java code (Windows-friendly)
    - name: Compile Java code
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path bin
        Get-ChildItem -Recurse -Filter *.java | ForEach-Object {
          javac -d bin $_.FullName
        }

    # 4. Optional: Run Main class
    - name: Run Main class
      shell: pwsh
      run: java -cp bin Main
