name: Java Build on Windows

# Trigger the workflow on push
on:
  push:
    branches:
      - main
      - '**'   # optional: triggers on any branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Java (you can change the version)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # 3. Compile Java code
    - name: Compile Java code
      run: |
        mkdir -p bin
        javac -d bin $(find . -name "*.java")

    # 4. Optional: Run Java program
    - name: Run Main class
      run: |
        java -cp bin Main
